### ISSUE TITLE
No rule to make target 'build/startup_stm32f030x8.o'

### ISSUE THREAD

**Issue by johschmitz** [adamheinrich/cm-makefile-examples#1]
So I did the following:
```
sudo apt install gcc-arm-none-eabi openocd
```
then
```
git clone --recursive https://github.com/adamheinrich/cm-makefile-examples.git
cd cm-makefile-examples/stm32-cube
make
```
But I get the following error:

> make: *** No rule to make target 'build/startup_stm32f030x8.o', needed by 'build/stm32-cube.elf'.  Stop.

What could be wrong or missing?

**Comment by johschmitz** [comment]
I also downloaded
`STM32Cube_FW_F4_V1.21.0`
now and put it into
`cm-makefile-examples/stm32-cube/`
as a subfolder
and changed
`CUBE_DIR = STM32Cube_FW_F4_V1.21.0`
but still the same error.

**Comment by johschmitz** [comment]
Okay got it, the example is for F0
so one needs
`STM32Cube_FW_F0_V1.9.0`
for example.

**Comment by adamheinrich** [comment]
Exactly. But changing it to F4 is quite simple: just replace `f0` wth `f4` and use the correct startup code (instead of `startup_stm32f030x8.S`) to match your MCU -- it is device-specific.

**Comment by johschmitz** [comment]
Note: In ubuntu it is also necessary to install
`libnewlib-arm-none-eabi`

**Comment by johschmitz** [comment]
I am wondering if the steps I took could be added to the README?
At least the last one with the newlib.

**Comment by johschmitz** [comment]
I submitted a pull request for the INSTALL.md.

**Comment by adamheinrich** [comment]
Oh, I didn't mention that the toolchain has to be installed from a PPA:

```
	sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
	suto apt-get update
	sudo apt-get install gcc-arm-embedded
```

Sorry for this.

**Comment by adamheinrich** [comment]
Fixed, thank you for pointing out. Feel free to create a PR with your way (`gcc-arm-embedded` + `libnewlib-arm-none-eabi`), it's nice to have alternatives.
